name = "drben-oficial"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
name = "drben-oficial"

[[env.production.routes]]
pattern = "drben.mauromoncao.adv.br/*"
zone_name = "mauromoncao.adv.br"
